const cover=document.querySelector('#cover'), invitation=document.querySelector('#invitation'), openButton=document.querySelector('#open-invitation');
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
let transitioning=false;
openButton.addEventListener('click',()=>{if(transitioning)return;transitioning=true;cover.classList.add('opening');setTimeout(()=>{cover.hidden=true;cover.style.display='none';invitation.hidden=false;window.scrollTo(0,0);requestAnimationFrame(()=>requestAnimationFrame(()=>invitation.classList.add('entered')));document.querySelector('.topbar a').focus({preventScroll:true});transitioning=false;},reduced?0:650);});
document.querySelector('#close-invitation').addEventListener('click',()=>{if(transitioning)return;transitioning=true;invitation.classList.remove('entered');setTimeout(()=>{invitation.hidden=true;cover.hidden=false;cover.style.display='grid';window.scrollTo(0,0);requestAnimationFrame(()=>cover.classList.remove('opening'));openButton.focus({preventScroll:true});transitioning=false;},reduced?0:650);});
if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));}else{document.querySelectorAll('.reveal').forEach(el=>el.classList.add('visible'));}
const dialog=document.querySelector('#photo-dialog');
document.querySelectorAll('.polaroid').forEach(button=>button.addEventListener('click',()=>{const image=button.querySelector('img');const large=document.querySelector('#large-photo');large.src=image.src;large.alt=image.alt;dialog.showModal();document.body.classList.add('modal-open');}));
document.querySelector('#close-photo').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});dialog.addEventListener('close',()=>document.body.classList.remove('modal-open'));
const gift=document.querySelector('#gift-link');const giftUrl=(window.INVITE_CONFIG?.giftListUrl||'').trim();if(/^https?:\/\//i.test(giftUrl)){gift.href=giftUrl;gift.target='_blank';gift.rel='noopener noreferrer';gift.removeAttribute('aria-disabled');document.querySelector('#gift-note').hidden=true;}else{gift.setAttribute('role','link');gift.setAttribute('tabindex','0');gift.addEventListener('click',e=>e.preventDefault());}
